# Generated by Django 5.0.7 on 2024-07-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_alter_apartment_number_alter_house_house_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('water_cost', models.FloatField()),
                ('maintenance_cost', models.FloatField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='house.apartment')),
            ],
        ),
    ]
