# Generated by Django 5.0.7 on 2024-07-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(max_length=10, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_water_tariff', models.BooleanField(default=False, verbose_name='Тариф на воду')),
                ('is_area_tariff', models.BooleanField(default=False, verbose_name='Тариф на СОИ')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=10, verbose_name='Номер квартиры')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='house.house', verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('serial_number', models.PositiveIntegerField(max_length=10, verbose_name='Серийный номер')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='house.apartment', verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Показания')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='house.watermeter', verbose_name='Счётчик')),
            ],
            options={
                'unique_together': {('water_meter', 'reading_date')},
            },
        ),
    ]
