# Generated by Django 5.0.7 on 2024-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.PositiveIntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='serial_number',
            field=models.PositiveIntegerField(verbose_name='Серийный номер'),
        ),
    ]
